export const configData_1 = [
{id:3101 , name: '冥司裁域 冥界',level:1 , skill: 100, initialSkill:100 , characteristic: 'wood', group : '神限'},
{id:3102 , name: '冥蝕廃域 冥界',level:1 , skill: 100, initialSkill:100 , characteristic: 'wood' , group : '神限'},
{id:3099 , name: '星涯焉者 電弧',level:1 , skill: 100, initialSkill:100 , characteristic: 'water', group : '神限'},
{id:3098 , name: '命涯憶者 電弧',level:1 , skill: 100, initialSkill:100 , characteristic: 'water', group : '神限'},
{id:3033 , name: '厳昇神蝕 日蝕',level:1 , skill: 90, initialSkill:90, characteristic: 'water', group : '神限'},
{id:3032 , name: '幻墜審蝕 日蝕',level:1 , skill: 90, initialSkill:90, characteristic: 'water', group : '神限'},
{id:3030 , name: '恒尽崩醒 流星',level:1 , skill: 90, initialSkill:90, characteristic: 'thunder', group : '神限'},
{id:3029 , name: '瞬輝鳳星 流星',level:1 , skill: 90, initialSkill:90, characteristic: 'thunder', group : '神限'},
{id:2992 , name: '聖霊祝使 黄泉',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:2991 , name: '幽生呪師 黄泉',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:2972 , name: '閃耀相姫 友愛',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:2971 , name: '光耀開姫 友愛',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:2969 , name: '赫灼魔帝 潛能',level:1 , skill: 100, initialSkill:100, characteristic: 'fire', group : '神限'},
{id:2968 , name: '赫焉獄帝 潛能',level:1 , skill: 100, initialSkill:100, characteristic: 'fire', group : '神限'},
{id:2932 , name: '魔煌神鬼 黄昏',level:1 , skill: 120, initialSkill:120, characteristic: 'thunder', group : '神限'},
{id:2931 , name: '機巧神姫 黄昏',level:1 , skill: 120, initialSkill:120, characteristic: 'thunder', group : '神限'},
{id:2891 , name: '劫火鳳凰 迷失',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:2890 , name: '終焉鳳凰 迷失',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:2888 , name: '癒賜鳳凰 重生',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:2887 , name: '命華鳳凰 重生',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:2841 , name: '雨露滴降 領域',level:1 , skill: 90, initialSkill:90, characteristic: 'water', group : '神限'},
{id:2840 , name: '雨露光環 領域',level:1 , skill: 90, initialSkill:90, characteristic: 'water', group : '神限'},
{id:2817 , name: '綺填究博 傳承',level:1 , skill: 90, initialSkill:90, characteristic: 'thunder', group : '神限'},
{id:2816 , name: '轟填剣博 傳承',level:1 , skill: 90, initialSkill:90, characteristic: 'thunder', group : '神限'},
{id:2814 , name: '不夜彩新 革新',level:1 , skill: 100, initialSkill:100, characteristic: 'fire', group : '神限'},
{id:2813 , name: '絶歌開新 革新',level:1 , skill: 100, initialSkill:100, characteristic: 'fire', group : '神限'},
{id:2776 , name: '幻想恒星 北極星',level:1 , skill: 90, initialSkill:90, characteristic: 'wood', group : '神限'},
{id:2775 , name: '夜空輝星 北極星',level:1 , skill: 90, initialSkill:90, characteristic: 'wood', group : '神限'},
{id:2745 , name: '減月獣神 霞月',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:2744 , name: '月光獣神 霞月',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:2742 , name: '滅陽獣神 破曉',level:1 , skill: 90, initialSkill:90, characteristic: 'fire', group : '神限'},
{id:2741 , name: '天道獣神 破曉',level:1 , skill: 90, initialSkill:90, characteristic: 'fire', group : '神限'},
{id:2684 , name: '零滅創皇 零',level:1 , skill: 90, initialSkill:90, characteristic: 'wood', group : '神限'},
{id:2683 , name: '絶訣破皇 零',level:1 , skill: 90, initialSkill:90, characteristic: 'wood', group : '神限'},
{id:2681 , name: '無限麗姫 無限',level:1 , skill: 60, initialSkill:60, characteristic: 'water', group : '神限'},
{id:2680 , name: '無限洸姫 無限',level:1 , skill: 60, initialSkill:60, characteristic: 'water', group : '神限'},
{id:2609 , name: '憐舞聖霊 新生',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:2608 , name: '悦舞聖霊 新生',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:2606 , name: '冥舞妖魔 死命',level:1 , skill: 90, initialSkill:90, characteristic: 'fire', group : '神限'},
{id:2605 , name: '閻舞妖魔 死命',level:1 , skill: 90, initialSkill:90, characteristic: 'fire', group : '神限'},
{id:2571 , name: '紫電極光 光束',level:1 , skill: 90, initialSkill:90, characteristic: 'thunder', group : '神限'},
{id:2570 , name: '燦爛極光 光束',level:1 , skill: 90, initialSkill:90, characteristic: 'thunder', group : '神限'},
{id:2539 , name: '慈水司神 大氣',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:2538 , name: '繁穣司神 大氣',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:2536 , name: '華光躍星 惑星',level:1 , skill: 90, initialSkill:90, characteristic: 'water', group : '神限'},
{id:2535 , name: '閃光躍星 惑星',level:1 , skill: 90, initialSkill:90, characteristic: 'water', group : '神限'},
{id:2592 , name: '燿傑錬術師 錬金',level:1 , skill: 100, initialSkill:100, characteristic: 'fire', group : '神限'},
{id:2591 , name: '灼廻錬術師 錬金',level:1 , skill: 100, initialSkill:100, characteristic: 'fire', group : '神限'},
{id:2463 , name: '冥眼邪統司 地獄',level:1 , skill: 60, initialSkill:60, characteristic: 'wood', group : '神限'},
{id:2462 , name: '深眼影統司 地獄',level:1 , skill: 60, initialSkill:60, characteristic: 'wood', group : '神限'},
{id:2460 , name: '瞳刃虹彩司 天堂',level:1 , skill: 90, initialSkill:90, characteristic: 'thunder', group : '神限'},
{id:2459 , name: '剣瞳聖彩司 天堂',level:1 , skill: 90, initialSkill:90, characteristic: 'thunder', group : '神限'},
{id:2450 , name: '天則司神 婆羅那',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:2449 , name: '三界創神 婆羅那',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:2399 , name: '精源輝姫 法力',level:1 , skill: 90, initialSkill:90, characteristic: 'wood', group : '神限'},
{id:2398 , name: '霊源森姫 法力',level:1 , skill: 90, initialSkill:90, characteristic: 'wood', group : '神限'},
{id:2396 , name: '相極魔装士 魔法',level:1 , skill: 60, initialSkill:60, characteristic: 'fire', group : '神限'},
{id:2395 , name: '炎帝魔刃 魔法',level:1 , skill: 60, initialSkill:60, characteristic: 'fire', group : '神限'},
{id:2356 , name: '星雲輝光 新星',level:1 , skill: 90, initialSkill:90, characteristic: 'thunder', group : '神限'},
{id:2355 , name: '連星輝光 新星',level:1 , skill: 90, initialSkill:90, characteristic: 'thunder', group : '神限'},
{id:2316 , name: '蒼碧滝結姫 水蓮',level:1 , skill: 80, initialSkill:80, characteristic: 'water', group : '神限'},
{id:2315 , name: '蒼瑞滝蓮姫 水蓮',level:1 , skill: 80, initialSkill:80, characteristic: 'water', group : '神限'},
{id:2313 , name: '焔翠龍鬼師 不知火',level:1 , skill: 60, initialSkill:60, characteristic: 'fire', group : '神限'},
{id:2312 , name: '妖焔喚龍師 不知火',level:1 , skill: 40, initialSkill:40, characteristic: 'fire', group : '神限'},
{id:2300 , name: '蒼銀双鎖天 天空',level:1 , skill: 90, initialSkill:90, characteristic: 'wood', group : '神限'},
{id:2299 , name: '碧琥双聖天 天空',level:1 , skill: 90, initialSkill:90, characteristic: 'wood', group : '神限'},
{id:2246 , name: '神預託宣者 神諭',level:1 , skill: 80, initialSkill:80, characteristic: 'thunder', group : '神限'},
{id:2245 , name: '神言伝託者 神諭',level:1 , skill: 80, initialSkill:80, characteristic: 'thunder', group : '神限'},
{id:2243 , name: '命運統女神 諾倫',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:2242 , name: '刻命時女神 諾倫',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:2213 , name: '彗渦滅星帝 銀河',level:1 , skill: 90, initialSkill:90, characteristic: 'water', group : '神限'},
{id:2212 , name: '焚創星帝 銀河',level:1 , skill: 90, initialSkill:90, characteristic: 'water', group : '神限'},
{id:2191 , name: '凛輝救世妃 彌賽亞',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:2190 , name: '秘憐救世妃 彌賽亞',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:2155 , name: '雷崇瞬術士 永恒',level:1 , skill: 40, initialSkill:40, characteristic: 'thunder', group : '神限'},
{id:2154 , name: '煌威流術士 永恒',level:1 , skill: 60, initialSkill:60, characteristic: 'thunder', group : '神限'},
{id:2152 , name: '創命の祈姫 起源',level:1 , skill: 80, initialSkill:80, characteristic: 'fire', group : '神限'},
{id:2151 , name: '起源の尊姫 起源',level:1 , skill: 80, initialSkill:80, characteristic: 'fire', group : '神限'},
{id:2099 , name: '焔雷の化身 憤怒',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:2098 , name: '憤怒の劫火 憤怒',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:2078 , name: '翠璃夢双姫 神秘',level:1 , skill: 80, initialSkill:80, characteristic: 'wood', group : '神限'},
{id:2077 , name: '玉響永幾姫 神秘',level:1 , skill: 80, initialSkill:80, characteristic: 'wood', group : '神限'},
{id:2075 , name: '天蒼幻想起 理想',level:1 , skill: 90, initialSkill:90, characteristic: 'water', group : '神限'},
{id:2074 , name: '天熾艶才起 理想',level:1 , skill: 90, initialSkill:90, characteristic: 'water', group : '神限'},
{id:2047 , name: '眩輝雷皇 神威',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:2046 , name: '竜烈雷師 神威',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:1981 , name: '暗鬼暗鏡 止水',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:1980 , name: '静澄輝鏡 止水',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:1955 , name: '堕天之剣聖 厄里斯',level:1 , skill: 130, initialSkill:130, characteristic: 'dark', group : '神限'},
{id:1954 , name: '冥獄ノ天剣 厄里斯',level:1 , skill: 130, initialSkill:130, characteristic: 'dark', group : '神限'},
{id:1932 , name: '歴浪樹緑神 永遠',level:1 , skill: 50, initialSkill:50, characteristic: 'wood', group : '神限'},
{id:1931 , name: '時旅碧翠神 永遠',level:1 , skill: 70, initialSkill:70, characteristic: 'wood', group : '神限'},
{id:1928 , name: '幻夢灼凍神 剎那',level:1 , skill: 80, initialSkill:80, characteristic: 'fire', group : '神限'},
{id:1927 , name: '無刻紅燃神 剎那',level:1 , skill: 80, initialSkill:80, characteristic: 'fire', group : '神限'},
{id:1890 , name: '罪斬廷女神 忒彌斯',level:1 , skill: 150, initialSkill:150, characteristic: 'light', group : '神限'},
{id:1889 , name: '裁秤聖女神 忒彌斯',level:1 , skill: 150, initialSkill:150, characteristic: 'light', group : '神限'},
{id:1789 , name: '命創源霹愛 夏娃',level:1 , skill: 80, initialSkill:80, characteristic: 'thunder', group : '神限'},
{id:1788 , name: '秘望哀霹愛 夏娃',level:1 , skill: 80, initialSkill:80, characteristic: 'thunder', group : '神限'},
{id:1785 , name: '蛇神罪業世 亞當',level:1 , skill: 90, initialSkill:90, characteristic: 'fire', group : '神限'},
{id:1784 , name: '命園統焔世 亞當',level:1 , skill: 90, initialSkill:90, characteristic: 'fire', group : '神限'},
{id:1702 , name: '蒼翠先天運 命運',level:1 , skill: 80, initialSkill:80, characteristic: 'water', group : '神限'},
{id:1701 , name: '凍焔後天運 命運',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:1639 , name: '転生雷導神 輪迴',level:1 , skill: 60, initialSkill:60, characteristic: 'thunder', group : '神限'},
{id:1638 , name: '転生閃渦神 輪迴',level:1 , skill: 70, initialSkill:70, characteristic: 'thunder', group : '神限'},
{id:1635 , name: '万象樹麗神 森羅',level:1 , skill: 80, initialSkill:80, characteristic: 'wood', group : '神限'},
{id:1634 , name: '万象翠宙神 森羅',level:1 , skill: 80, initialSkill:80, characteristic: 'wood', group : '神限'},
{id:1545 , name: '業極天命 業力',level:1 , skill: 60, initialSkill:60, characteristic: 'fire', group : '神限'},
{id:1544 , name: '業華輪廻 業力',level:1 , skill: 60, initialSkill:60, characteristic: 'fire', group : '神限'},
{id:1458 , name: '創世の幻妃 起源',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:1457 , name: '創世の魔妃 起源',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:1454 , name: '終祈審判者 啟示錄',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:1453 , name: '終願叶祈者 啟示錄',level:1 , skill: 100, initialSkill:100, characteristic: 'water', group : '神限'},
{id:1385 , name: '源啓秘昇霊 靈魂',level:1 , skill: 80, initialSkill:80, characteristic: 'thunder', group : '神限'},
{id:1384 , name: '源啓灼蝕霊 靈魂',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:1270 , name: '終焉閃爆神 諸神黃昏',level:1 , skill: 60, initialSkill:60, characteristic: 'fire', group : '神限'},
{id:1269 , name: '終焉潤闇神 諸神黃昏',level:1 , skill: 60, initialSkill:60, characteristic: 'fire', group : '神限'},
{id:1211 , name: '光淵の澄雫 以太',level:1 , skill: 80, initialSkill:80, characteristic: 'water', group : '神限'},
{id:1210 , name: '碧落の幻雫 以太',level:1 , skill: 80, initialSkill:80, characteristic: 'water', group : '神限'},
{id:1114 , name: '聖羽の流輝女 妮姬',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:1113 , name: '天祈の勝戦女神 妮姬',level:1 , skill: 100, initialSkill:100, characteristic: 'wood', group : '神限'},
{id:1055 , name: '彗粒瞬星宙 宇宙',level:1 , skill: 100, initialSkill:100, characteristic: 'fire', group : '神限'},
{id:1054 , name: '光隕瞬星宙 宇宙',level:1 , skill: 100, initialSkill:100, characteristic: 'fire', group : '神限'},
{id:973 , name: '神託の軍聖女 貞德',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:972 , name: '天啓の軍聖女 貞德',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:951 , name: '創世醒彗神 混亂',level:1 , skill: 70, initialSkill:70, characteristic: 'water', group : '神限'},
{id:950 , name: '創世瀑翼神 混亂',level:1 , skill: 120, initialSkill:120, characteristic: 'water', group : '神限'},
{id:910 , name: '滅塵焉果律 奧米加',level:1 , skill: 90, initialSkill:90, characteristic: 'fire', group : '神限'},
{id:909 , name: '業炎焉果律 奧米加',level:1 , skill: 90, initialSkill:90, characteristic: 'fire', group : '神限'},
{id:847 , name: '零帰序因律 阿爾法',level:1 , skill: 120, initialSkill:120, characteristic: 'wood', group : '神限'},
{id:846 , name: '創世序因律 阿爾法',level:1 , skill: 80, initialSkill:80, characteristic: 'wood', group : '神限'},
{id:796 , name: '雷轟永劫龍 銜尾蛇',level:1 , skill: 100, initialSkill:100, characteristic: 'thunder', group : '神限'},
{id:795 , name: '創蒼永劫龍 銜尾蛇',level:1 , skill: 120, initialSkill:120, characteristic: 'thunder', group : '神限'},
];

export const configData_2 = [
{id:3094 , name: '十二鬼月上弦の参猗窩座(無限城編ver.)',level:1 , skill: 120, initialSkill:120 , characteristic: 'fire', group : '鬼滅', sp: true,},
{id:3093 , name: '十二鬼月上弦の陸獪岳',level:1 , skill: 150, initialSkill:150 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:3092 , name: '火雷神我妻善逸',level:1 , skill: 100, initialSkill:100 , characteristic: 'thunder', group : '鬼滅', sp: true,},
{id:3091 , name: '水柱冨岡義勇(痣発現ver.)',level:1 , skill: 120, initialSkill:120 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:3089 , name: '百足蛇腹胡蝶しのぶ',level:1 , skill: 90, initialSkill:90 , characteristic: 'wood', group : '鬼滅', sp: true,},
{id:3088 , name: '岩柱悲鳴嶼行冥',level:1 , skill: 90, initialSkill:90 , characteristic: 'fire', group : '鬼滅', sp: true,},
{id:3087 , name: '冨岡義勇＆竈門炭治郎',level:1 , skill: 120, initialSkill:120 , characteristic: 'fire', group : '鬼滅', sp: true,},
{id:3086 , name: '竈門炭治郎＆冨岡義勇',level:1 , skill: 120, initialSkill:120 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:3085 , name: '錆兎',level:1 , skill: 90, initialSkill:90 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:3084 , name: '蛇柱伊黒小芭内',level:1 , skill: 90, initialSkill:90 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:3083 , name: '風柱不死川実弥',level:1 , skill: 90, initialSkill:90 , characteristic: 'wood', group : '鬼滅', sp: true,},
{id:2801 , name: '十二鬼月上弦の肆憎珀天',level:1 , skill: 120, initialSkill:120 , characteristic: 'thunder', group : '鬼滅', sp: true,},
{id:2800 , name: '十二鬼月上弦の伍玉壺(真の姿)',level:1 , skill: 120, initialSkill:120 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:2799 , name: '不死川玄弥',level:1 , skill: 90, initialSkill:90 , characteristic: 'thunder', group : '鬼滅', sp: true,},
{id:2798 , name: '霞柱時透無一郎',level:1 , skill: 100, initialSkill:100 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:2797 , name: '十二鬼月上弦の肆哀絶',level:1 , skill: 190, initialSkill:190 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:2796 , name: '十二鬼月上弦の肆空喜',level:1 , skill: 160, initialSkill:160 , characteristic: 'fire', group : '鬼滅', sp: true,},
{id:2795 , name: '十二鬼月上弦の肆可楽',level:1 , skill: 130, initialSkill:130 , characteristic: 'wood', group : '鬼滅', sp: true,},
{id:2794 , name: '十二鬼月上弦の肆積怒',level:1 , skill: 120, initialSkill:120 , characteristic: 'thunder', group : '鬼滅', sp: true,},
{id:2793 , name: '不死川玄弥＆竈門炭治郎',level:1 , skill: 100, initialSkill:100 , characteristic: 'thunder', group : '鬼滅', sp: true,},
{id:2792 , name: '竈門炭治郎＆不死川玄弥',level:1 , skill: 100, initialSkill:100 , characteristic: 'fire', group : '鬼滅', sp: true,},
{id:2791 , name: '鋼鐵塚蛍',level:1 , skill: 70, initialSkill:70 , characteristic: 'thunder', group : '鬼滅', sp: true,},
{id:2790 , name: '竈門炭治郎＆竈門禰豆子(爆血刀ver.)',level:1 , skill: 150, initialSkill:150 , characteristic: 'fire', group : '鬼滅', sp: true,},
{id:2789 , name: '恋柱甘露寺蜜璃',level:1 , skill: 120, initialSkill:120 , characteristic: 'wood', group : '鬼滅', sp: true,},
{id:2666 , name: '十二鬼月上弦の陸妓夫太郎',level:1 , skill: 150, initialSkill:150 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:2665 , name: '十二鬼月上弦の陸堕姫',level:1 , skill: 120, initialSkill:120 , characteristic: 'wood', group : '鬼滅', sp: true,},
{id:2664 , name: '音柱宇髄天元',level:1 , skill: 90, initialSkill:90 , characteristic: 'thunder', group : '鬼滅', sp: true,},
{id:2663 , name: '蟲柱胡蝶しのぶ',level:1 , skill: 50, initialSkill:50 , characteristic: 'wood', group : '鬼滅', sp: true,},
{id:2662 , name: '水柱冨岡義勇',level:1 , skill: 80, initialSkill:80 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:2661 , name: '炎柱煉獄杏寿郎',level:1 , skill: 120, initialSkill:120 , characteristic: 'fire', group : '鬼滅', sp: true,},
{id:2660 , name: '十二鬼月上弦の参猗窩座',level:1 , skill: 100, initialSkill:100 , characteristic: 'wood', group : '鬼滅', sp: true,},
{id:2659 , name: '十二鬼月下弦の壱魘夢',level:1 , skill: 150, initialSkill:150 , characteristic: 'thunder', group : '鬼滅', sp: true,},
{id:2658 , name: '十二鬼月下弦の伍累',level:1 , skill: 150, initialSkill:150 , characteristic: 'fire', group : '鬼滅', sp: true,},
{id:2657 , name: '我妻善逸＆嘴平伊之助	',level:1 , skill: 120, initialSkill:120 , characteristic: 'wood', group : '鬼滅', sp: true,},
{id:2656 , name: '我妻善逸＆嘴平伊之助',level:1 , skill: 120, initialSkill:120 , characteristic: 'thunder', group : '鬼滅', sp: true,},
{id:2655 , name: '最終選別竈門炭治郎',level:1 , skill: 120, initialSkill:120 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:2654 , name: '鱗滝左近次',level:1 , skill: 100, initialSkill:100 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:2653 , name: '栗花落カナヲ',level:1 , skill: 80, initialSkill:80 , characteristic: 'wood', group : '鬼滅', sp: true,},
{id:2652 , name: '嘴平伊之助',level:1 , skill: 90, initialSkill:90 , characteristic: 'wood', group : '鬼滅', sp: true,},
{id:2651 , name: '竈門禰豆子',level:1 , skill: 90, initialSkill:90 , characteristic: 'water', group : '鬼滅', sp: true,},
{id:2650 , name: '我妻善逸',level:1 , skill: 100, initialSkill:100 , characteristic: 'thunder', group : '鬼滅', sp: true,},
{id:2649 , name: 'ヒノカミ神楽竈門炭治郎覚醒ver.',level:1 , skill: 30, initialSkill:30 , characteristic: 'fire', group : '鬼滅', sp: true,},
{id:2648 , name: 'ヒノカミ神楽＆水の呼吸竈門炭治郎',level:1 , skill: 380, initialSkill:380 , characteristic: 'fire', group : '鬼滅', sp: true,},
];

export const configData =[...configData_1,...configData_2];